config/routes.rb
Rails.application.routes.draw do
  resources :pro_football_references
  resources :workers

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
end

app/controllers/pro_football_references_controller.rb
class ProFootballReferencesController < ApplicationController
  def new
  end

  def create
    PfrPlayerDataWorker.perform_async(params[:scraper])
    redirect_to pro_football_references_path
  end

  def destroy
  end

  def index; end
end

app/helpers/pro_football_reference_helper.rb
module ProFootballReferenceHelper
end

app/views/pro_football_references/create.html.slim
h1 ProFootballReference#create
p Find me in app/views/pro_football_reference/create.html.slim

app/views/pro_football_references/destroy.html.slim
h1 ProFootballReference#destroy
p Find me in app/views/pro_football_reference/destroy.html.slim

app/views/pro_football_references/index.html.slim
= link_to "Start Scraping", new_pro_football_reference_path 
div.container-fluid.admin-task
  h4 Active Tasks
  div#active_workers_table
    table.table.worker-table
      thead
        tr
          th Task
          th Time Enqueued
          th Time Started
          th Elapsed Time (s)
  br

javascript:
  $(function() {
    $('.tasks-table').DataTable({
      'scrollY': '500px',
      'paging': false,
      'scrollCollapse': true
    });
    var workerTable = $('.worker-table').DataTable({
      paging: false,
      scrollCollapse: true,
      ajax: {
        url: '/workers',
        type: 'GET',
        dataSrc: function(json) {
          return json;
        }
      },
      columnDefs: [
          {
            targets: 0,
            render: function (data, type, row) {
              return row.worker;
            }
          },
          {
            targets: 1,
            render: function (data, type, row) {
              return row.enqueued_at;
            }
          },
          {
            targets: 2,
            render: function (data, type, row) {
              return row.created_at;
            }
          },
          {
            targets: 3,
            render: function (data, type, row) {
              return row.elapsed_at;
            }
          }
        ]
    });
    setInterval( function () {
      workerTable.ajax.reload();
    }, 3000 );
  });

app/views/pro_football_references/new.html.slim
h1 Time to get some data?
h4 If so, press one of the buttons below.
= button_to "Scrape Team Data", { action: "create", scraper: "team_data" },
                                  data:  { confirm: "Start getting player data?" },
                                  class: "btn btn-default"
= button_to "Scrape Player Data", { action: "create", scraper: "player_data" },
                                  data:  { confirm: "Start getting player data?" },
                                  class: "btn btn-default"
= button_to "Scrape Season Data", { action: "create", scraper: "season_stats" },
                                  data:  { confirm: "Start getting player data?" },
                                  class: "btn btn-default"